name: Publish Python Package

on:
  push:
    tags:
      - 'v*.*.*'  # (ad es. v1.0.0)
    branches:
      - development  # Aggiungi questo per i commit su branch development

jobs:
  build:
    runs-on: ubuntu-latest
    environment: release
    permissions:
      id-token: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.7'

      - name: Install Poetry
        run: pip install poetry

      - name: Cache Poetry dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cache/pypoetry
          key: ${{ runner.os }}-poetry-${{ hashFiles('**/poetry.lock') }}
          restore-keys: |
            ${{ runner.os }}-poetry-

      - name: Install dependencies
        run: poetry install

      # - name: Run tests
      #   run: poetry run pytest  # Assumendo che tu usi pytest per i test

      - name: Build package
        run: poetry build

      - name: Publish package distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1

  publish-dev:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/development'  # Questo job si esegue solo per il branch development
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.7'

      - name: Install Poetry
        run: pip install poetry

      - name: Cache Poetry dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cache/pypoetry
          key: ${{ runner.os }}-poetry-${{ hashFiles('**/poetry.lock') }}
          restore-keys: |
            ${{ runner.os }}-poetry-

      - name: Install dependencies
        run: poetry install

      # - name: Run tests
      #   run: poetry run pytest  # Assumendo che tu usi pytest per i test

      - name: Build package
        run: poetry build

      - name: Publish package distributions to GitHub Packages
        uses: actions/upload-artifact@v3
        with:
          name: dist
          path: dist/*
